### ISSUE TITLE
As a CS student, I want to be able to create my own account so I can gain access to my profile.

### ISSUE THREAD

**Issue by MayankJ99** [UB-CSE/course-project-a9-collegehub#2]
Acceptance Test:
1. Go to the homepage at /
2. Go to sign up through the button
3. Fill up the form for sign up
4. Receive verification email
4. Click the link in the email to verify 
5. Head on over to login
6. Enter credentials
7. Gain access to the profile

**Comment by clincl** [comment]
User Story Formatting
